site_name: 'AVDASI 2 docs'
site_url: https://avdai2.github.io/docs
theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: flightlab
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: flightlab_dark
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
  - navigation.tracking
  - navigation.instant
  - navigation.search
  - navigation.search.highlight
  - navigation.search.suggestions
  - navigation.search.suggestions.highlight
  #- navigation.tabs
  - navigation.sections
  - navigation.indexes
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  - content.code.expand
  - content.code.highlight
  - content.code.tabs
  - content.code.toggle
  - content.code.wrap
  - content.code.include
  - content.code.include.highlight
  - content.code.include.tabs
  - content.code.include.toggle
  - content.code.include.wrap
  - content.code.include.tabs
  - navigation.instant.progress
  - navigation.instant.preview
  - navigation.footer
  language: en
plugins:
 # - search
 # - literate-nav:
 #      nav_file: index.md
 #      implicit_index: true
  - glightbox
 # - git-revision-date-localized:
 #     fallback_to_build_date: true
markdown_extensions:
  - codehilite
  - footnotes
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UoBFlightLab

nav:
  - Home: index.md
  - Avionics:
    - avionics/index.md
    - Step-by-step guide:
      - avionics/stepbystep/index.md
      - 00. Kit:              avionics/stepbystep/00-kit.md
      - 01. Cube:             avionics/stepbystep/01-cube.md
      - 02. Mission Planner:  avionics/stepbystep/02-missionplanner.md
      #- 03. Power:            avionics/stepbystep/03-power.md
      #- 04. Servos:           avionics/stepbystep/04-servos.md
      #- 05. Telemetry:        avionics/stepbystep/05-telemetry.md
      #- 06. Radio control:    avionics/stepbystep/06-rc.md
      #- 07. Data logging:     avionics/stepbystep/07-datalog.md
      #- 08. PyMAVLink:        avionics/stepbystep/08-pymavlink.md
      #- 09. I2C:              avionics/stepbystep/09-i2c.md
      #- 10. Luascript:        avionics/stepbystep/10-lua.md
      #- 99. Summary:          avionics/stepbystep/99-summary.md
    - Example Code: avionics/examplecode.md
    - Expert links: avionics/links.md
  - Mechanisms: 
    - mechanisms/index.md
